select
  c.TABLE_NAME, 
  c.COLUMN_NAME, 
  c.DATA_TYPE, 
  c.CHARACTER_MAXIMUM_LENGTH ,
  c.NUMERIC_PRECISION,
  c.NUMERIC_SCALE,
  c.IS_NULLABLE
from INFORMATION_SCHEMA.COLUMNS c
where table_name = 'TABLE_NAME'
  and column_name IN('COLUMN_NAME_1', 'COLUMN_NAME_2', 'COLUMN_NAME_3');
